name: Python application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner

    steps:
    - uses: actions/checkout@v2

    - name: Clear the pip cache
      run: |
        python -m pip cache purge

    - name: Set up Python 3.1
      uses: actions/setup-python@v2
      with:
        python-version: 3.1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if test -f requirements.txt; then pip install -r requirements.txt;  # Corrected the conditional statement

    - name: Activate virtual environment
      run: |
        path\to\your\virtualenv\Scripts\activate  # Replace with the actual path to your virtual environment

    - name: Run pytest
      run: |
        pytest
